import referrerPolicy = require('../..')
import connect = require('connect')

connect().use(referrerPolicy())
connect().use(referrerPolicy({}))
connect().use(referrerPolicy({ policy: 'no-referrer' }))
connect().use(referrerPolicy({ policy: 'no-referrer-when-downgrade' }))
connect().use(referrerPolicy({ policy: 'same-origin' }))
connect().use(referrerPolicy({ policy: 'origin' }))
connect().use(referrerPolicy({ policy: 'strict-origin' }))
connect().use(referrerPolicy({ policy: 'origin-when-cross-origin' }))
connect().use(referrerPolicy({ policy: 'strict-origin-when-cross-origin' }))
connect().use(referrerPolicy({ policy: 'unsafe-url' }))
connect().use(referrerPolicy({ policy: '' }))
